<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'VideoDownloader' or $(MSBuildProjectName.StartsWith('VideoDownloader.'))">
    <Version>1.0.19</Version>
    <AssemblyTitle>Video Downloader</AssemblyTitle>
    <Product>Video Downloader</Product>
    <Company>VideoDownloader</Company>
  </PropertyGroup>
</Project>
